### ISSUE TITLE
SSLContext support

### ISSUE THREAD

**Issue by innovationchef** [ibm-messaging/mq-dev-patterns#10]
[JMS]
I can't find support for SSLContext to provide TLS args instead of setting it using system properties.

**Comment by chughts** [comment]
Can you please elucidate on your question. 

For JMS the location of the keystore comes in as a command line parameter eg. 

`-Djavax.net.ssl.trustStore=/your_key_directory/clientkey.jks`

and the cipher spec / suite is set in the application eg. 

`cf.setStringProperty(WMQConstants.WMQ_SSL_CIPHER_SUITE, CIPHER_SUITE);`

In the JMS samples in this repository the applications read the `CIPHER_SUITE` information from the app.json file.

**Comment by innovationchef** [comment]
I meant, instead of passing the keystore and truststore as command line parameters, can we not create a SslContext.java class object and pass it as a parameter to the connectionFactory object?
Like - 

```
 private static JmsConnectionFactory createJMSConnectionFactory() {
    JmsFactoryFactory ff;
    JmsConnectionFactory cf;
    try {
      ff = JmsFactoryFactory.getInstance(WMQConstants.WMQ_PROVIDER);
      cf = ff.createConnectionFactory();
      cf.setSslContext(sslContext);
    } catch (JMSException jmsex) {
      recordFailure(jmsex);
      cf = null;
    }
    return cf;
  }
```

Here is how I am planning to create a sslContext object - 

```
SSLContext sslContext = null;
try(FileInputStream keyStoreInput = new FileInputStream(keyStoreLocation);
	FileInputStream trustStoreInput = new FileInputStream(trustStoreLocation)) {
        KeyStore keyStore = KeyStore.getInstance("PKCS12");
	keyStore.load(keyStoreInput, keystorePassword.toCharArray());
	KeyStore trustStore = KeyStore.getInstance("JKS");
	trustStore.load(trustStoreInput, truststorePassword.toCharArray());
	TrustManagerFactory trustManagerFactory = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
	KeyManagerFactory keyManagerFactory = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());

	trustManagerFactory.init(trustStore);
	keyManagerFactory.init(keyStore, keystorePassword.toCharArray());

	sslContext = SSLContext.getInstance("SSLv3");

	// Initialize our SSL context from the key/trust managers
	sslContext.init(keyManagerFactory.getKeyManagers(), trustManagerFactory.getTrustManagers(), null);
catch (Exception e) {
        e.printStackTrace();
}
```

**Comment by chughts** [comment]
No, you can't do that currently, though there is a related RFE which you can add your vote to - https://www.ibm.com/developerworks/rfe/execute?use_case=viewRfe&CR_ID=130693
