### ISSUE TITLE
JMS Samples with CCDT.json file - NoClassDefFoundError: org/json/JSONException

### ISSUE THREAD

**Issue by danielorlan** [ibm-messaging/mq-dev-patterns#11]
Was receiving runtime exception when using CCDT from json file in `JMS/com/ibm/mq/samples/jms/JmsPut.java`
I had to add an additional json jar (`json-20190722.jar`) to the class path to get it working

`javac -cp ./com.ibm.mq.allclient-9.1.3.0.jar:./javax.jms-api-2.0.1.jar:./json-simple-1.1.1.jar:./json-20190722.jar:. com/ibm/mq/samples/jms/JmsPut.java`

`java -cp ./com.ibm.mq.allclient-9.1.3.0.jar:./javax.jms-api-2.0.1.jar:./json-simple-1.1.1.jar:./json-20190722.jar:. com.ibm.mq.samples.jms.JmsPut`

### Logs with the err msg:
> Mar 01, 2020 7:37:32 PM com.ibm.mq.samples.jms.SampleEnvSetter getCheckForCCDT
> INFO: Checking for existance of file /Users/danielorlan/dev/repos/mq-dev-patterns/ccdt.json
> Mar 01, 2020 7:37:32 PM com.ibm.mq.samples.jms.JmsPut main
> INFO: Put application is starting
> Mar 01, 2020 7:37:32 PM com.ibm.mq.samples.jms.JmsPut setJMSProperties
> INFO: Will be making use of CCDT File file:///Users/danielorlan/dev/repos/mq-dev-patterns/ccdt.json
> Mar 01, 2020 7:37:32 PM com.ibm.mq.samples.jms.JmsPut main
> INFO: created connection factory
> Exception in thread "main" java.lang.NoClassDefFoundError: org/json/JSONException
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
> 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
> 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at com.ibm.mq.jmqi.system.internal.CCDTFileParser.newInstance(CCDTFileParser.java:129)
> 	at com.ibm.mq.jmqi.system.internal.CCDT.<init>(CCDT.java:111)
> 	at com.ibm.mq.jmqi.remote.impl.RemoteCCDT.<init>(RemoteCCDT.java:62)
> 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.getCcdt(RemoteFAP.java:486)
> 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.access$2200(RemoteFAP.java:187)
> 	at com.ibm.mq.jmqi.remote.api.RemoteFAP$Connector.initialiseFromCCDT(RemoteFAP.java:13950)
> 	at com.ibm.mq.jmqi.remote.api.RemoteFAP$Connector.jmqiConnect(RemoteFAP.java:13024)
> 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiConnect(RemoteFAP.java:1339)
> 	at com.ibm.mq.jmqi.remote.api.RemoteFAP.jmqiConnect(RemoteFAP.java:1303)
> 	at com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.jmqiConnect(InterceptedJmqiImpl.java:377)
> 	at com.ibm.mq.ese.jmqi.ESEJMQI.jmqiConnect(ESEJMQI.java:562)
> 	at com.ibm.msg.client.wmq.internal.WMQConnection.<init>(WMQConnection.java:371)
> 	at com.ibm.msg.client.wmq.factories.WMQConnectionFactory.createV7ProviderConnection(WMQConnectionFactory.java:8475)
> 	at com.ibm.msg.client.wmq.factories.WMQConnectionFactory.createProviderConnection(WMQConnectionFactory.java:7815)
> 	at com.ibm.msg.client.jms.admin.JmsConnectionFactoryImpl._createConnection(JmsConnectionFactoryImpl.java:303)
> 	at com.ibm.msg.client.jms.admin.JmsConnectionFactoryImpl.createContext(JmsConnectionFactoryImpl.java:444)
> 	at com.ibm.mq.samples.jms.JmsPut.main(JmsPut.java:69)
> Caused by: java.lang.ClassNotFoundException: org.json.JSONException
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 29 more

**Comment by chughts** [comment]
@danielorlan Thanks for the information. I need to investigate what is happening. The required json.jar file is refereed to in the allclient.jar pom.xml as a pre-requisite, so should get pulled in, but doesn't appear to be. I think I already had it on my machine. 

As I said I need to work out what is happening on a cleaner machine.
