### ISSUE TITLE
Sample basicget.js fails (NodeJs samples)

### ISSUE THREAD

**Issue by djarrin** [ibm-messaging/mq-dev-patterns#17]
I've been trying for a little while and I can't seem to get the samples that I run on my local machine to connect to the docker MQ instance I stood up. I followed these [instructions](https://developer.ibm.com/tutorials/mq-connect-app-queue-manager-containers/#step-4-put-and-get-a-message-using-the-mq-console) and I'm able to get to https://localhost:9443/ibmmq/console. When downloading these packages (and running npm install) and I attempt to run `node basicget.js` I get the error `Error Detected making Connection MQError: CONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_KEY_REPOSITORY_ERROR [2381]`. Is there a step that is missing from the readme about setting up a "key repository"?

**Comment by chughts** [comment]
`basicget.js` has this bit of code:

````
    if (MQDetails.KEY_REPOSITORY) {
      debug_info('Will be running in TLS Mode');

      cd.SSLCipherSpec = MQDetails.CIPHER;
      cd.SSLClientAuth = MQC.MQSCA_OPTIONAL;
    }
````

Which means that if there is an entry for KEY_REPOSITORY in the env.json file, then the connection will be over TLS. In which case a CIPHER needs to be specified and KEY_REPOSITORY should point at a valid key store and key stash.  Guidance on TLS setup is available in the main repo readme - https://github.com/ibm-messaging/mq-dev-patterns

If you haven't enabled TLS on your docker image then remove KEY_REPOSITORY from env.json.

**Comment by djarrin** [comment]
Thanks @chughts that did it.
