### ISSUE TITLE
Question: How to i set the pub/sub as persistant dot net

### ISSUE THREAD

**Issue by SaethorP** [ibm-messaging/mq-dev-patterns#18]
Hi I am trying this out locally using docker and the dot net sample

I have tried having multiple subscriber to a topic but i want the messages to be persistent so that if one subscriber dies it can start again where it left of, instead of missing out. 

This did not work
`producer = sessionWMQ.CreateProducer(destination);
            producer.DeliveryMode = DeliveryMode.Persistent;`

Could you maybe help me with the configuration of the pub/sub demo.

**Comment by chughts** [comment]
You also need to modify the subscriber to create a durable subscription. So instead of 

```c#
            // Create subscriber
            subscriber = sessionWMQ.CreateConsumer(destination);
```

you would need

```c#
            // Create subscriber
            subscriber = sessionWMQ.CreateDurableSubscriber(destination, "app specific durable subscription id"); 
```
API reference can be found - 
https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.2.0/com.ibm.mq.ref.dev.doc/sapisess.htm#sapisess_crdursub

**Comment by SaethorP** [comment]
@chughts thanks that worked. 👍
