### ISSUE TITLE
Clean: Unecessary condition 

### ISSUE THREAD

**Issue by proteck** [ibm-messaging/mq-dev-patterns#239]
The following condition is useless.

https://github.com/ibm-messaging/mq-dev-patterns/blob/a870110f90f3c01e1ce13067385cf09e87a0dfaf/SpringBoot-MVC/src/main/resources/static/script.js#L95-L99

**Comment by chughts** [comment]
@harshitsharma2801 
probably only need to add the message to the div if the put was successful.

**Comment by chughts** [comment]
fixed.
