### ISSUE TITLE
Improve the dotnet samples

### ISSUE THREAD

**Issue by StevenLiekens** [ibm-messaging/mq-dev-patterns#3]
I'm an experienced .NET developer and I noticed that the XMS samples for .NET can be improved in the following ways:

## 1. Add Missing Project Files

The samples contain only C# files (`.cs`).  
The project (`.csproj`) and solution (`.sln`) files that are needed to compile the code are missing.

**Action needed**: add the missing csproj and sln files to https://github.com/ibm-messaging/mq-dev-patterns/tree/master/dotnet.

## 2. Publish MQ Client to NuGet

Referencing DLLs that are installed in `C:\Program Files` is an outdated practice. In modern .NET development, libraries should be published as packages to NuGet.

**Action needed**: publish MQ Client DLLs as a NuGet package on https://nuget.org.

## 3. Rename the Executable

The README uses the name `dotnet.exe` for the compiled sample program. That name is overloaded and confusing: `dotnet.exe` is also the name of the [.NET Core command-line interface](https://github.com/dotnet/cli#basic-usage).

**Action needed**: rename `dotnet.exe` to something more meaningful like `TryXMS.exe`

**Comment by oljarast** [comment]
Thanks for your feedback.
1. Included .csproj and .sln files 
2. Unfortunately we can't currently add MQ Client libraries to NuGet due to the fact that nuget.org do not provide the ability to enforce US Export regulations.
3. Hope the rename is ok. 
We'll test once more and pull in if ok.

**Comment by StevenLiekens** [comment]
> Unfortunately we can't currently add MQ Client libraries to NuGet due to the fact that nuget.org do not provide the ability to enforce US Export regulations.

This really is a massive blocker for automating builds and deploys, because you don't want to install a specific version of the MQ Client libraries on a shared build server. Cloud providers like Azure Pipelines don't even allow installing dependencies to C:\Program Files on a cloud-hosted build server.

**Comment by oljarast** [comment]
> > Unfortunately we can't currently add MQ Client libraries to NuGet due to the fact that nuget.org do not provide the ability to enforce US Export regulations.
> 
> This really is a massive blocker for automating builds and deploys, because you don't want to install a specific version of the MQ Client libraries on a shared build server. Cloud providers like Azure Pipelines don't even allow installing dependencies to C:\Program Files on a cloud-hosted build server.

Thanks for the feedback again. 
We'll keep trying with the NuGet thing, in the meantime, you might find the Windows client libraries in the redistributable client zip form useful, available from [here](http://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqdev/redist/).

**Comment by oljarast** [comment]
@StevenLiekens and @danielsteinmann 
We've included some .Net info on our LearnMQ site
https://developer.ibm.com/messaging/learn-mq/mq-tutorials/develop-mq-xms-dotnet/ 
We'd appreciate any feedback
