### ISSUE TITLE
issue running qpid-quarkus example

### ISSUE THREAD

**Issue by dabkhazi** [ibm-messaging/mq-dev-patterns#55]
I followed all the necessary steps to run the qpid examples.  I built and run ibm mq server 9.2.3. Qpid-standart example works well. When running qpid-quarkus i got an error:

AMQXR0100E: A connection from 172.17.0.1 was not authorized. [condition = amqp:unauthorized-access]

**Comment by chughts** [comment]
As it works when running with qpid standard, then I am guessing that the user / password credentials that are not being set correctly in the quid-quarkus variant. 

As per https://github.com/ibm-messaging/mq-dev-patterns/blob/master/amqp-qpid/qpid-quarkus/README.md

> The properties that the samples need to connect to MQ are in the resources/application.properties file.
> 
> quarkus.qpid-jms.url
> MQ AMQP URI set to amqp://localhost:5672
> quarkus.qpid-jms.username
> MQ app username
> quarkus.qpid-jms.password
> MQ app password
