### ISSUE TITLE
Is any one of this examples show IBMMQ->push java, i.e no polling?

### ISSUE THREAD

**Issue by anborg** [ibm-messaging/mq-dev-patterns#67]
Is any one of this examples show IBMMQ->push java, i.e no polling?

I dont want the java app to keep polling the queue/server/topic -- i.e multiple hits to server. I want something that is push based, i.e when queue has a message, the java program receives the message -- similar to event based.

Does such a thing exist in IBMMQ-java?

**Comment by ibmmqmet** [comment]
Read about JMS MessageListeners. There's a sample in the MQ product - /opt/mqm/samp/jms/samples/simple/JmsResponder.java

**Comment by maxkahan** [comment]
There's also a basic sample for a JMS message listener as mentioned above on github here: https://github.com/ibm-messaging/mq-dev-samples/tree/master/DemoMessageListenerApplication
