### ISSUE TITLE
Example for other ways to apply CCDT related settings

### ISSUE THREAD

**Issue by wilkovanderveen** [ibm-messaging/mq-dev-patterns#69]
The dotnet ccdt example uses environment variables to get the CCDT path. Is there another way to get this setting? Being dependent on the environment is introducing an extra dependency in my opinion.

**Comment by chughts** [comment]
The environment setting for CCDT Path is used by the underlying MQ Client code, so it needs to be set before a connection is made. These samples check if it is, then ensure that the connection is made in such a way to not override the CCDT settings. 

You can have the application set the environment setting based on other criteria, but the environment setting needs to be in place before a connection to MQ is made,

**Comment by wilkovanderveen** [comment]
The underlying MQ client seems to be kind of closed source, but there is really no need to use windows environment variables to connect to the MQ server. It would be very nice and makes things much more easier for .NET developers to implement the options pattern and dependency injection for the .NET core client.

**Comment by chughts** [comment]
We could make the CCDT path part of the env.json file, and process it in the same way the other env.json settings are processed.

**Comment by wilkovanderveen** [comment]
@chughts that would be a nice start.

**Comment by wilkovanderveen** [comment]
@micheleissa that looks nice. Mine is over [https://github.com/wilkovanderveen/ChickenBanana.IbmMqClientTools](here).

**Comment by wilkovanderveen** [comment]
@micheleissa where can we find the completed change sugessted by @chughts ?

**Comment by micheleissa** [comment]
@wilkovanderveen  I think it was just a suggestion and it was not implemented.
