### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by jwende** [ibm-messaging/mq-dev-patterns#8]
error response:
C:\2_Git\mq-dev-patterns\Node.js\node_modules\ref-napi>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:362:16)
gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:139:11)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:181:9)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\2_Git\mq-dev-patterns\Node.js\node_modules\ref-napi
gyp ERR! node -v v8.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>

**Comment by chughts** [comment]
Is this failing on the `npm install`?  It looks like its failing building `node-gyp`, which going by its documentation has a dependancy on `Python`, `make` and a `C/C++` compiler. 

What happens if you try to install node-gyp directly? eg.

npm install node-gyp

**Comment by ibmmqmet** [comment]
From https://github.com/ibm-messaging/mq-mqi-nodejs/blob/master/README.md :

> I have run it on Windows, where the NPM 'windows-build-tools' package also needed to be installed first.
