### ISSUE TITLE
Restrict Backout to 3 tries

### ISSUE THREAD

**Issue by hussainsam** [ibm-messaging/mq-dev-patterns#89]
Hi,

I am trying to implement Backout queue and refered this sample
[CmdRunner115.java](https://github.com/ibm-messaging/mq-dev-patterns/blob/master/Spring-JMS/src/main/java/com/ibm/mq/samples/jms/spring/level115/CmdRunner115.java)

I don't seem to understand, how can I set the threshold to 3. I want to send the message to Backout queue when there are 3 hits to retrieve the message. Also from the sample it doesn't show anywhere that I can define a backout queue name. Could you please clear these 2 confusion. How can I set the threshold to 3 and where can I define my backup queueName in the code listed in the samples

**Comment by chughts** [comment]
The IBM MQ AllClient JMS classes will take care of the threshold check and will move the message to the backout queue. All you need to do is set the threshold and backout queue. See - https://www.ibm.com/docs/en/ibm-mq/9.0?topic=applications-handling-poison-messages-in-mq-classes-jms

Setting the threshold and backout queue is a queue level configuration setting, which can be set using the MQ Console. 

![Uploading Screenshot 2022-08-30 at 10.33.53.png…]()

**Comment by chughts** [comment]
<img width="726" alt="Screenshot 2022-08-30 at 10 33 53" src="https://user-images.githubusercontent.com/10371360/187404139-25096991-c68d-4a87-b86f-11c64e6d897d.png">

**Comment by hussainsam** [comment]
Thank you very much for the quick response on suggesstion. Do you know if there is a way to set these settings programmatically ? I have access to the Queue but since MQs are running in test containers, I cannot access the Console to set the settings from UI

**Comment by chughts** [comment]
You can, but its a question that you should really ask on StackOverflow. 

For example you can use the REST admin API. To view the swagger page for the REST API go to https://<your MQ Server URL>:<Your MQ Server PORT>/ibm/api/explorer 

there your will find the API to modify a queue https://web-qm1-85c0.qm.us-south.mq.appdomain.cloud/ibm/api/explorer/#!/queue/modifyQueue where you can set `backoutRequeueQueueName` and `backoutThreshold` as well as any one of 


```json
{
  "cluster": {
    "namelist": "string",
    "qmgrId": "string",
    "name": "string",
    "qmgrName": "string",
    "queueType": "string",
    "workloadQueueUse": "string",
    "workloadPriority": 0,
    "transmissionQueueForChannelName": "string",
    "workloadRank": 0
  },
  "timestamps": {
    "created": "string",
    "clustered": "string",
    "altered": "string"
  },
  "queueSharingGroup": {
    "disposition": "string",
    "structureName": "string",
    "qmgrName": "string"
  },
  "storage": {
    "indexType": "string",
    "storageClass": "string",
    "maximumDepth": 0,
    "pageSet": 0,
    "maximumMessageLength": 0,
    "messageDeliverySequence": "string",
    "nonPersistentMessageClass": "string"
  },
  "trigger": {
    "initiationQueueName": "string",
    "depth": 0,
    "data": "string",
    "processName": "string",
    "messagePriority": 0,
    "type": "string",
    "enabled": true
  },
  "remote": {
    "queueName": "string",
    "transmissionQueueName": "string",
    "qmgrName": "string"
  },
  "extended": {
    "allowSharedInput": true,
    "enableMediaImageOperations": "string",
    "backoutRequeueQueueName": "string",
    "hardenGetBackout": true,
    "custom": "string",
    "supportDistributionLists": true,
    "backoutThreshold": 0
  },
  "applicationDefaults": {
    "putResponse": "string",
    "messagePriority": 0,
    "messagePersistence": "string",
    "clusterBind": "string",
    "sharedInput": true,
    "readAhead": "string",
    "messagePropertyControl": "string"
  },
  "general": {
    "inhibitPut": true,
    "inhibitGet": true,
    "isTransmissionQueue": true,
    "description": "string"
  },
  "alias": {
    "targetName": "string",
    "targetType": "string"
  },
  "model": {
    "type": "string"
  },
  "dynamic": {
    "type": "string"
  },
  "events": {
    "serviceInterval": {
      "highEnabled": true,
      "okEnabled": true,
      "duration": 0
    },
    "depth": {
      "lowPercentage": 0,
      "highPercentage": 0,
      "lowEnabled": true,
      "fullEnabled": true,
      "highEnabled": true
    }
  },
  "dataCollection": {
    "accounting": "string",
    "monitoring": "string",
    "statistics": "string"
  },
  "status": {
    "tpipeName": [
      "string"
    ]
  },
  "name": "string",
  "type": "string"
}
```
