### ISSUE TITLE
Dotnet Sample - cloned subscription

### ISSUE THREAD

**Issue by Bjego** [ibm-messaging/mq-dev-patterns#91]
Can you please provide a sample how to use cloned/shared subscriptions with XMS.NET?

I want to create a publish / subscribe solution within our buisness. The app will run in kubernetes and may scale horizontally on load, when the app scales horizontally, I don't want that every pod consumes and processes a message on a topic.

Example given:

- Subscriber#1 for Service "NewsProcessor" on pod 1 subscribes to topic "dev/news/+"
- Subscriber#2 for Service "NewsProcessor" on pod 2 subscribes to topic "dev/news/+"
- Subscriber#3 for Service "AllProcessor" on pod 3 subscribes to topic "dev/#"
- Publisher publishes message "new employee added" on topic "dev/news/employees"

Only Subscriber Subscriber#3 and Subscriber#1 should pocess the message.

Setting up this scenario is quite easy in kafka, but I can't get it working with IBM MQ and XMS.NET (IBMXMSDotnetClient V. 9.3.0)

Thanks in advance

**Comment by chughts** [comment]
I think the .net subscribe sample already does that 

- https://github.com/ibm-messaging/mq-dev-patterns/blob/master/dotnet/dotNetSub.cs

**Comment by Bjego** [comment]
@chughts hmm.. haven't seen that - how do I have to configure and run it? Where is the hidden gem, I am missing?

**Comment by chughts** [comment]
Follow the readme - https://github.com/ibm-messaging/mq-dev-patterns/blob/master/dotnet/README.md

**Comment by Bjego** [comment]
Thank you , will try that. Going to close this issue.
