### ISSUE TITLE
Upgrading dotnet client to be on .NET 6.0

### ISSUE THREAD

**Issue by micheleissa** [ibm-messaging/mq-dev-patterns#93]
I'm thinking it is time to move from windows-only .NET framework to the latest version .NET 6.0
Any thoughts or concerns? I can take a look at converting the solution and pushing a pull request

Thanks

**Comment by chughts** [comment]
A pull request would be much appreciated. I will be asking @RamSubbarao to review, when you have the PR ready.

**Comment by micheleissa** [comment]
I have created a draft pull request #94 
I took the liberty on modifying the `README.md` file to reflect the changes, please feel free to put notes regarding that or anything else. Thanks

**Comment by chughts** [comment]
pull request has been reviewed and accepted.
